# set echo folder locations here
raw_input_path = "../datasets/echo/unsegregated frames/"
raw_label_path = "../datasets/echo/unsegregated groundtruth/"
renamed_input_path = "../datasets/echo/renamed frames/"
renamed_label_path = "../datasets/echo/renamed groundtruth/"

# paths below are for the images and groundtruth
l_traindata = "../datasets/echo/train_groundtruth/"                # labels for training set
trainInput_data = "../datasets/echo/train/"
l_testdata = "../datasets/echo/test_groundtruth/"                  # labels for test set
testInput_data = "../datasets/echo/test/"
l_validdata = "../datasets/echo/valid_groundtruth/"                # labels for validation set
validInput_data = "../datasets/echo/valid/"

# paths below are for the masks generated by the U-Net model
training_mask_path = "./model/training_masks/"
validating_mask_path = "./model/validating_masks/"
testing_mask_path = "./model/testing_masks/"

# path below are for the csv file generated from the dataset for the summary of labels
echo_labels = "../datasets/echo/echo_data.csv"

# path below is the location for dataset label for A4C images
dataset_label = "../datasets/echo/A4C.xlsx"
    